#!/bin/bash
set -eo pipefail

_create_configmap() {
    kubectl apply -f yamlConfig/configmap.yaml
}

_create_deployment() {
  kubectl apply -f yamlConfig/deployment.yaml
  kubectl rollout status deploy dobby
}

_create_service() {
  kubectl apply -f yamlConfig/service.yaml
}

__deploy() {
  _create_configmap
  _create_deployment
  _create_service
}

usage_message="Usage $0 <command>\nCommands:"

CMD=${1:-}
shift || true
if __${CMD} "$@"; then ## Functions to be called as commands are prefixed with __
  exit 0
else
  echo -e "$usage_message\n$(declare -F | sed -n "s/declare -f __/ - /p")"
fi