apiVersion: v1
kind: Service
metadata:
  labels:
    app: dobby
  name: dobby-service
spec:
  type: NodePort
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
    nodePort: 30202
  selector:
    app: dobby